// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record_OptionCode int32

const (
	Record_UNSPECIFIED Record_OptionCode = 0
	Record_OPTION_1    Record_OptionCode = 1
	Record_OPTION_2    Record_OptionCode = 2
)

// Enum value maps for Record_OptionCode.
var (
	Record_OptionCode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "OPTION_1",
		2: "OPTION_2",
	}
	Record_OptionCode_value = map[string]int32{
		"UNSPECIFIED": 0,
		"OPTION_1":    1,
		"OPTION_2":    2,
	}
)

func (x Record_OptionCode) Enum() *Record_OptionCode {
	p := new(Record_OptionCode)
	*p = x
	return p
}

func (x Record_OptionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Record_OptionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_record_proto_enumTypes[0].Descriptor()
}

func (Record_OptionCode) Type() protoreflect.EnumType {
	return &file_record_proto_enumTypes[0]
}

func (x Record_OptionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Record_OptionCode.Descriptor instead.
func (Record_OptionCode) EnumDescriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0, 0}
}

// 同一要素名のEnumは同一メッセージ内に定義できない（protobufの仕様）
type Record_SubOption_OptionCode int32

const (
	Record_SubOption_UNSPECIFIED Record_SubOption_OptionCode = 0
	Record_SubOption_OPTION_1    Record_SubOption_OptionCode = 1
	Record_SubOption_OPTION_2    Record_SubOption_OptionCode = 2
)

// Enum value maps for Record_SubOption_OptionCode.
var (
	Record_SubOption_OptionCode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "OPTION_1",
		2: "OPTION_2",
	}
	Record_SubOption_OptionCode_value = map[string]int32{
		"UNSPECIFIED": 0,
		"OPTION_1":    1,
		"OPTION_2":    2,
	}
)

func (x Record_SubOption_OptionCode) Enum() *Record_SubOption_OptionCode {
	p := new(Record_SubOption_OptionCode)
	*p = x
	return p
}

func (x Record_SubOption_OptionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Record_SubOption_OptionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_record_proto_enumTypes[1].Descriptor()
}

func (Record_SubOption_OptionCode) Type() protoreflect.EnumType {
	return &file_record_proto_enumTypes[1]
}

func (x Record_SubOption_OptionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Record_SubOption_OptionCode.Descriptor instead.
func (Record_SubOption_OptionCode) EnumDescriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Option    *Record_Option    `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	SubOption *Record_SubOption `protobuf:"bytes,3,opt,name=sub_option,json=subOption,proto3" json:"sub_option,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetOption() *Record_Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *Record) GetSubOption() *Record_SubOption {
	if x != nil {
		return x.SubOption
	}
	return nil
}

// 同一要素名のEnumは同一メッセージ内に定義できない（protobufの仕様）
//
//	enum SubOptionCode {
//	  UNSPECIFIED = 0;
//	  OPTION_1 = 1;
//	  OPTION_2 = 2;
//	}
type Record_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionCode Record_OptionCode `protobuf:"varint,1,opt,name=option_code,json=optionCode,proto3,enum=protobuf_optional.Record_OptionCode" json:"option_code,omitempty"`
}

func (x *Record_Option) Reset() {
	*x = Record_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record_Option) ProtoMessage() {}

func (x *Record_Option) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record_Option.ProtoReflect.Descriptor instead.
func (*Record_Option) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Record_Option) GetOptionCode() Record_OptionCode {
	if x != nil {
		return x.OptionCode
	}
	return Record_UNSPECIFIED
}

type Record_SubOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionCode Record_SubOption_OptionCode `protobuf:"varint,1,opt,name=option_code,json=optionCode,proto3,enum=protobuf_optional.Record_SubOption_OptionCode" json:"option_code,omitempty"`
}

func (x *Record_SubOption) Reset() {
	*x = Record_SubOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record_SubOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record_SubOption) ProtoMessage() {}

func (x *Record_SubOption) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record_SubOption.ProtoReflect.Descriptor instead.
func (*Record_SubOption) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Record_SubOption) GetOptionCode() Record_SubOption_OptionCode {
	if x != nil {
		return x.OptionCode
	}
	return Record_SubOption_UNSPECIFIED
}

var File_record_proto protoreflect.FileDescriptor

var file_record_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x22, 0xbc, 0x03, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x75, 0x62, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x73, 0x75, 0x62, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x4f, 0x0a, 0x06, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x0a, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x97, 0x01, 0x0a, 0x09,
	0x53, 0x75, 0x62, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x0b, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x75, 0x62, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x0a, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x50, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x50, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x32, 0x10, 0x02, 0x22, 0x39, 0x0a, 0x0a, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x31,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x32, 0x10, 0x02,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x37,
	0x34, 0x74, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x67, 0x6f, 0x2f, 0x32,
	0x30, 0x32, 0x34, 0x30, 0x37, 0x33, 0x30, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData = file_record_proto_rawDesc
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_proto_rawDescData)
	})
	return file_record_proto_rawDescData
}

var file_record_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_record_proto_goTypes = []interface{}{
	(Record_OptionCode)(0),           // 0: protobuf_optional.Record.OptionCode
	(Record_SubOption_OptionCode)(0), // 1: protobuf_optional.Record.SubOption.OptionCode
	(*Record)(nil),                   // 2: protobuf_optional.Record
	(*Record_Option)(nil),            // 3: protobuf_optional.Record.Option
	(*Record_SubOption)(nil),         // 4: protobuf_optional.Record.SubOption
}
var file_record_proto_depIdxs = []int32{
	3, // 0: protobuf_optional.Record.option:type_name -> protobuf_optional.Record.Option
	4, // 1: protobuf_optional.Record.sub_option:type_name -> protobuf_optional.Record.SubOption
	0, // 2: protobuf_optional.Record.Option.option_code:type_name -> protobuf_optional.Record.OptionCode
	1, // 3: protobuf_optional.Record.SubOption.option_code:type_name -> protobuf_optional.Record.SubOption.OptionCode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record_SubOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		EnumInfos:         file_record_proto_enumTypes,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_rawDesc = nil
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
